# Generated by Django 2.2.7 on 2019-11-22 10:15

from django.db import migrations, models
import xlib.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=xlib.utils.generate_uid, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=3000, null=True)),
                ('photo', models.URLField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'event ',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EventTag',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=xlib.utils.generate_uid, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('events', models.ManyToManyField(related_name='tags', to='event.Event')),
            ],
            options={
                'db_table': 'event.event_tag',
                'managed': True,
            },
        ),
    ]
