# Generated by Django 2.2.7 on 2019-11-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
