# Generated by Django 2.2.7 on 2019-11-20 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('email',)},
        ),
    ]
