# Generated by Django 2.2.7 on 2019-12-02 11:15

from django.db import migrations, models
import user.models.user


class Migration(migrations.Migration):

    dependencies = [
        ('event_user', '0002_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(null=True, upload_to=user.models.user._content_file_name),
        ),
    ]
