# Generated by Django 2.2.7 on 2019-11-22 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import xlib.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0002_event_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=xlib.utils.generate_uid, primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=130)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'event.comment',
                'managed': True,
            },
        ),
    ]
